name: Core
description: ${project.description}
version: ${project.version}
main: in.mineforest.core.paper.PaperEngine
author: ${author}
api-version: "1.13"
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
commands:
  forward_command:
    description: Executes a command when the player is forward facing
    usage: /forward_command <command>
    permission: forward_command.use
