file-version: 1

database:
  host: ""
  port: 3306
  name: ""
  username: ""
  password: ""

report:
  webhook: "https://discordapp.com/api/webhooks/1324424462615052318/7H9xISASdYl70GnZuXD2Or4Ll0pqyP7kfspNpmazm3BpP5lc8ZckeHisqmCOzsIsfwLs"
  types:
    CHEATING:
      description: "Using hacks, mods, or exploits to gain an unfair advantage."
      exception: "Anarchy servers."
    CHAT_ABUSE:
      description: "Harassment, hate speech, or inappropriate language in chat."
      exception: "Anarchy servers."
    BUG_ABUSE:
      description: "Exploiting game bugs for personal advantage."
      exception: "None, except dupes in anarchy servers."
    SPAMMING:
      description: "Repeatedly sending unnecessary or disruptive messages."
      exception: "None."
    IMPERSONATION:
      description: "Pretending to be another player or staff member."
      exception: "None."
    SCAMMING:
      description: "Attempting to defraud other players."
      exception: "LifeSteal and anarchy servers."
    TOXICITY:
      description: "Consistently exhibiting rude or disruptive behavior."
      exception: "None."
    INAPPROPRIATE_NAME:
      description: "Using an offensive or unsuitable player name."
      exception: "None."
    OFFENSIVE_SKIN:
      description: "Wearing an offensive or inappropriate character skin."
      exception: "None."
    OFFENSIVE_PAINTING:
      description: "Using an offensive or inappropriate character painting."
      exception: "None."

maintenance-support:
  webhook: "https://discordapp.com/api/webhooks/1324422897581949100/kNtSO4huIVyiUYHceDGTVE_Afd8jy8uRAqOjU2I0NyrRboAe7vlwuLxItr9Va1PqCVRh"
  discord-message: "{server_name} is undergoing maintenance! ETA: {eta}. <@&1307343734723182624>"
